% Setup
tl = ThirdLayer2DLabeler (...
        '/esat/sadr/amartino/monge428New/data2/',...
        'monge428New_lowres',...
        'pcl_gt_train.ply',...
        'pcl_gt_test_old.ply',...
        'pcl.ply',...
        'pcl_split.mat'...
    );

%%
tl.Project2DOntoPointCloud('SVM');

%%
% Weight vector format
% 3D 2D 2D_det pairwise
w = [0 1 0 0.5];
tl.LabelPointCloud(w);

%%
tl.splitName='monge428New_lowres_2D_3DCRF';
%%
tl.SplitPointCloud();

%%
tl.OrthoImages();

%%
tl.RunThirdLayer();

%%

highRes = false;
tls = cell(1,3);
if highRes
    tls{1} = ThirdLayer2DLabeler (...
        '/esat/sadr/amartino/monge428New/data/',...
        'monge428New_fullRes',...
        '3D_3DCRF',...
        'fullRes_pcloud_test_new_GCO.ply',...
        'fullRes_mesh_colors_normals.ply',...
        'fullRes_mesh_splitData.mat'...
    );

    tls{2} = ThirdLayer2DLabeler (...
        '/esat/sadr/amartino/monge428New/data/',...
        'monge428New_fullRes',...
        'layer1_3DCRF',...
        'fullRes_pcloud_test_new_GCO.ply',...
        'fullRes_mesh_colors_normals.ply',...
        'fullRes_mesh_splitData.mat'...
    );

    tls{3} = ThirdLayer2DLabeler (...
        '/esat/sadr/amartino/monge428New/data/',...
        'monge428New_fullRes',...
        'layer1+3D_3DCRF',...
        'fullRes_pcloud_test_new_GCO.ply',...
        'fullRes_mesh_colors_normals.ply',...
        'fullRes_mesh_splitData.mat'...
    );
else
        
    tls{1} = ThirdLayer2DLabeler (...
        '/esat/sadr/amartino/monge428New/data/',...
        'monge428New',...
        '3D_3DCRF',...
        'pcloud_gt_test_new_GCO.ply',...
        'mesh_colors_normals.ply',...
        'splitData.mat'...
    );

    tls{2} = ThirdLayer2DLabeler (...
        '/esat/sadr/amartino/monge428New/data/',...
        'monge428New',...
        'layer1_3DCRF',...
        'pcloud_gt_test_new_GCO.ply',...
        'mesh_colors_normals.ply',...
        'splitData.mat'...
    );

    tls{3} = ThirdLayer2DLabeler (...
        '/esat/sadr/amartino/monge428New/data/',...
        'monge428New',...
        'layer1+3D_3DCRF',...
        'pcloud_gt_test_new_GCO.ply',...
        'mesh_colors_normals.ply',...
        'splitData.mat'...
    );
    
end

tl = tls{3};
afaf
%%
% Split into individual facades
tl.SplitPointCloud();
   
% Fit planes to facades
tl.FitPlanes();
   
% Project to planes
tl.OrthoImages2();

% Run 2D third layer
tl.condorEnabled = true;
tl.RunThirdLayer();
    
%%
% If run through condor
if tl.condorEnabled
    tl.WaitForCondor();
end

%%
% Project labeling onto 3D point cloud of each facade
tl.OrthoImagesBackProject();

% Combine point clouds
tl.ReassemblePointCloud();

% Evaluate the labeling
score=tl.EvaluateLabeling()
