function [x,y,z,nx,ny,nz,r,g,b] = ImportPointCloud(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [X,Y,Z,NX,NY,NZ,R,G,B] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [X,Y,Z,NX,NY,NZ,R,G,B] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [x,y,z,nx,ny,nz,r,g,b] = importfile('option-0000.ply',14, 76468);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/09/10 17:52:49

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 14;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
x = dataArray{:, 1};
y = dataArray{:, 2};
z = dataArray{:, 3};
nx = dataArray{:, 4};
ny = dataArray{:, 5};
nz = dataArray{:, 6};
r = dataArray{:, 7};
g = dataArray{:, 8};
b = dataArray{:, 9};

